device/urls.py
from django.urls import path

from .views import DeviceAddView,DeviceListView,DeviceInfoDetailView,DeleteDeviceView,VideoPlayView
urlpatterns=[
    path("add",DeviceAddView.as_view(),name="add"),
    path("list",DeviceListView.as_view(),name="list"),
    path("detail/<device_id>",DeviceInfoDetailView.as_view(),name="detail"),
    path("delete/<device_id>",DeleteDeviceView.as_view(),name="delete"),
    path("videoplay",VideoPlayView.as_view(),name="videoplay"),
]

finally_project/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path,include
from .settings import MEDIA_URL,MEDIA_ROOT
from django.views.generic import TemplateView
from users.views import IndexView,ProductIntroductView
from device.views import UploadView,DisplayVideoView



urlpatterns = [
    path('admin/', admin.site.urls),
    path("displayvideo",DisplayVideoView.as_view(),name="displayvideo"),
    path("uploadvideo",UploadView.as_view(),name="uploadvideo"),
    path("users/",include(("users.urls","users"),namespace="users")),
    path("index/",IndexView.as_view(),name="index"),
    path("device/",include(("device.urls","device"),namespace="device")),
    path("product_introduction/",ProductIntroductView.as_view(),name="product_introduction"),
]
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import LoginView,RegisterView,LogoutView,AddLeavingMessageView,Mamage_Account_View
from .views import ManageInfoView,ChangePasswordView,ResetPasswordView,SetPasswordView,ConcatUsView,ConcatView

urlpatterns=[
    path("login",LoginView.as_view(),name="login"),
    path('register',RegisterView.as_view(),name="register"),
    path("logout",LogoutView.as_view(),name="logout"),
    path("addmessage/",AddLeavingMessageView.as_view(),name="add_message"),
    path("manage_account",Mamage_Account_View.as_view(),name="manage_account"),
    path("manage_info",ManageInfoView.as_view(),name="manage_info"),
    path("change_password",ChangePasswordView.as_view(),name="change_password"),
    path('reset_password',ResetPasswordView.as_view(),name="reset_password"),
    path('set_password',SetPasswordView.as_view(),name="set_password"),
    path('concat_us',ConcatUsView.as_view(),name="concat_us"),
    path('concat/',ConcatView.as_view(),name="concat"),
]

device/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User=get_user_model()

class Device(models.Model):

    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="所属用户")
    status=models.CharField(max_length=20,choices=(("OFFLINE","离线"),("ONLINE","在线"),("ABNORMAL","异常")),verbose_name="设备状态",default="OFFLINE")
    device_name=models.CharField(max_length=50,verbose_name="设备名称")
    device_id=models.CharField(max_length=100,verbose_name="设备ID")
    belonged_product=models.CharField(max_length=30,verbose_name="所属产品")
    product_type=models.CharField(max_length=30,verbose_name="设备类型")

    class Meta:
        verbose_name="设备"
        verbose_name_plural=verbose_name


class Video(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="所属用户")
    path=models.CharField(max_length=500,verbose_name="视频存储路径")
    name=models.CharField(max_length=200,verbose_name="视频名称")
    add_time=models.DateTimeField(auto_now_add=True,verbose_name="添加时间")
    class Meta:
        verbose_name="视频对象"
        verbose_name_plural=verbose_name

templates/add_device.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}添加设备{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
</head>
<body>
   {% block content %}
       <form class="form-horizontal col-sm-offset-4 " role="form" style="margin-top: 300px" method="post" action="{% url 'device:add' %}">
              <div class="form-group">
                <label for="firstname" class="col-sm-2 control-label">设备名称</label>
                <div class="col-sm-3">
                  <input type="text" class="form-control" id="firstname" placeholder="设备名称" name="device_name">
                </div>
              </div>
              <div class="form-group">
                <label for="lastname" class="col-sm-2 control-label">设备标识</label>
                <div class="col-sm-3">
                  <input type="text" class="form-control" id="lastname" placeholder="设备表示" name="imsi">
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-default">添加</button>
                </div>
              </div>
       {% csrf_token %}
       </form>
   {% endblock %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}模板{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../../static/css/css2.css">
    {% block js %}{% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse" role="navigation" style="display: block;margin-bottom: 0">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">首页</a>
            </div>
            <div>
                <ul class="navbar-nav">
                     <li class="active"><a href="#">我的设备</a></li>
                     <li><a href="#">订阅管理</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown " style="padding-left: 1200px;display: block">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                            <img width="39" height="30" src="http://127.0.0.1:8000/media/{{ MEDIA_URL }}{{ request.user.image }}"/>
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="margin-left: 1250px;" >
                            <a class="dropdown-item" href='#' >个人信息</a>
                            <a class="dropdown-item" href='{% url 'users:logout' %}' >退出登录</a>
                        </div>
                     </li>
                    {% else %}
                    <li class="nav-item " style="padding-left: 1200px">
                        <a class="nav-link" href="{% url 'users:login' %}" style="display: inline-block">登录</a>
                        <a class="nav-link" href="{% url 'users:register' %}" style="display: inline-block">注册</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <div id="copyright_box">
        <div id="finally_project_footer" class="column">
            <ul class="footer_column_t">
                <li><a href="#">关于我们</a></li>
                <li><a href="#">开发助手</a></li>
                <li><a href="#">联系我们</a></li>
                 <li><a href="#">在线客服</a></li>
            </ul>
        </div>
    </div>
</body>
</html>

templates/concact_us.html
<!DOCTYPE html>
{% extends 'index1.html' %}
<html lang="zh-CN">
<head>
	{% block title %}联系我们{% endblock %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block css %}
        <link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/fonts/font-awesome.min.css">
        <link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/select2.min.css">
        <link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/util.css">
        <link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/main.css">
        <style>
             * {
                 padding: 0;
                 margin: 0;
             }
             .slider {
                 background: none;
                 min-height:120px;
                 background-color: black;
                 margin: 0 5px;
             }
             .main {
                margin: 0 auto;
                padding: 50px 0;
                width: 1000px;
                min-height: 400px;
            }
        </style>
    {% endblock %}
	
</head>
{% block background %}{% endblock %}
{% block content %}
    <div class="dowebok container-contact100">
	<div class="wrap-contact100">
		<form class="contact100-form validate-form" id="jsbtnform">
			<span class="contact100-form-title">联系我们</span>

			<div class="wrap-input100 validate-input" data-validate="姓名不能为空">
				<label class="label-input100" for="name">姓名</label>
				<input id="name" class="input100" type="text" name="name" placeholder="请输入姓名">
				<span class="focus-input100"></span>
			</div>

			<div class="wrap-input100 validate-input" data-validate="请收入合法的邮箱地址">
				<label class="label-input100" for="email">电子邮箱</label>
				<input id="email" class="input100" type="text" name="email" placeholder="请输入电子邮箱">
				<span class="focus-input100"></span>
			</div>

			<div class="wrap-input100">
				<div class="label-input100">需要什么服务？</div>
				<div>
					<select class="js-select2" name="service">
						<option>请选择</option>
						<option>产品咨询</option>
						<option>问题反馈</option>
						<option>在线服务</option>
					</select>
					<div class="dropDownSelect2"></div>
				</div>
				<span class="focus-input100"></span>
			</div>

			<div class="wrap-input100 validate-input" data-validate="留言不能为空">
				<label class="label-input100" for="message">留言</label>
				<textarea id="message" class="input100" name="message" placeholder="请输入留言"></textarea>
				<span class="focus-input100"></span>
			</div>

			<div class="container-contact100-form-btn">
				<button class="contact100-form-btn" id="jsbtn1">提 交</button>
			</div>

			<div class="contact100-form-social flex-c-m">
				<a href="#" class="contact100-form-social-item flex-c-m bg1 m-r-20" target="_blank">
					<i class="fa fa-wechat" aria-hidden="true"></i>
				</a>

				<a href="#" class="contact100-form-social-item flex-c-m bg2 m-r-20" target="_blank">
					<i class="fa fa-qq" aria-hidden="true"></i>
				</a>

				<a href="#" class="contact100-form-social-item flex-c-m bg3" target="_blank">
					<i class="fa fa-weibo" aria-hidden="true"></i>
				</a>
			</div>
            {% csrf_token %}
		</form>

		<div class="contact100-more flex-col-c-m" style="background-image: url('https://first-1257059002.cos.ap-nanjing.myqcloud.com/images/bg-01.jpeg');">
		</div>
        <script>
            $(".js-select2").each(function(){
                $(this).select2({
                    minimumResultsForSearch: 20,
                    dropdownParent: $(this).next('.dropDownSelect2')
                });
            })
            $(".js-select2").each(function(){
                $(this).on('select2:open', function (e){
                    $(this).parent().next().addClass('eff-focus-selection');
                });
            });
            $(".js-select2").each(function(){
                $(this).on('select2:close', function (e){
                    $(this).parent().next().removeClass('eff-focus-selection');
                });
            });
        </script>
	</div>
</div>
{% endblock %}
{% block js %}
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery-1.12.4.min.js"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/select3.min.js"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/main.js"></script>
        <script>
            $(function () {
                $('#jsbtn1').on('click',function () {
                    $.ajax({
                        cache:false,
                        type:'POST',
                        url:"{% url "users:concat" %}",
                        data:$('#jsbtnform').serialize(),
                        async:true,
                        success:function (data) {
                            if(data.status=="success"){
                                $('#jsbtnform')[0].reset();
                                alert("感谢您的留言")
                            }
                            else if(data.status=='fail'){
                                $('#jsbtnform')[0].reset();
                                alert("表单填写错误")
                            }
                        },
                    });
                });
            })
        </script>
{% endblock %}
</html>

templates/device_list.html
<!DOCTYPE html>
<html lang="en" class="no-js">
{% extends 'index1.html' %}
<head>
	<meta charset="utf-8" />
	<title>{% block title %}设备列表{% endblock %}</title>
    {% block css %}
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/uniform.default.css" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" type="text/css" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/select2_metro.css" />
	    <link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/DT_bootstrap.css" />
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/style-metronic.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/style1.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/custom.css" rel="stylesheet" type="text/css"/>
        <link href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/modalBox.css" rel="stylesheet" type="text/css"/>
        <style>
             * {
                 padding: 0;
                 margin: 0;
             }
             .slider {
                 background: none;
                 min-height:120px;
                 background-color: black;
                 margin: 0 5px;
             }
        </style>
    {% endblock %}
    {% block js %}
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/respond.min.js"></script>
	    <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/excanvas.min.js"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com//js/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery.cookie.min.js" type="text/javascript"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery.uniform.min.js" type="text/javascript" ></script>
        <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/jquery.dataTables.js"></script>
        <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/DT_bootstrap.js"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/app.js"></script>
        <script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/table-editable.js"></script>
        <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/select2.min.js"></script>
        <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/Echarts.js"></script>
        <script>
            jQuery(document).ready(function() {
               App.init();
               TableEditable.init();
            });
        </script>
        <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/layer/layer.js"></script>
    {% endblock %}
</head>
{% block background %}{% endblock %}
{% block content %}
    <div class="page-container">
        <div class="page-content" style="margin-left: 0">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- /.modal -->
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN STYLE CUSTOMIZER -->
			<!-- END BEGIN STYLE CUSTOMIZER -->
			<!-- BEGIN PAGE HEADER-->
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="device_data" style="width: 100%;background-image: url('https://first-1257059002.cos.ap-nanjing.myqcloud.com/images/bg2.jpg');height:400px ">
                        <div class="device_info" style="height: 100%;width: 500px;box-shadow: 10px 10px 5px rgba(0,0,0,0);float: left">
                            <div class="inline_box" style="width: 50%;height: 30%;float: left;margin-top: 10px">
                                <h2 style="color: white;display: inline-block;padding-left: 40px;padding-top: 40px;">设备总数</h2>
                                <p style="color: white;display: inline-block;padding-left: 72px;font-size: 40px;padding-top: 20px;">{{ device_num }}</p>
                            </div>
                            <div class="inline_box" style="width: 50%;height: 30%;float: left;margin-top: 10px">
                                <h2 style="color: white;display: inline-block;padding-left: 40px;padding-top: 40px;">在线设备</h2>
                                <p style="color: white;display: block;padding-left: 72px;font-size: 40px;padding-top: 5px;color: white">{{ online }}</p>
                            </div>
                            <div class="inline_box" style="width: 50%;height: 30%;float: left;margin-top: 30px">
                                <h2 style="color: white;display: inline-block;padding-left: 40px;padding-top: 40px;">离线设备</h2>
                                <p style="color: white;display: block;padding-left: 72px;font-size: 40px;padding-top: 5px;color: white">{{ offline }}</p>
                            </div>
                            <div class="inline_box" style="width: 50%;height: 30%;float: left;margin-top: 30px">
                                <h2 style="color: white;display: inline-block;padding-left: 40px;padding-top: 40px;">异常设备</h2>
                                <p style="color: white;display: block;padding-left: 72px;font-size: 40px;padding-top: 5px;color: white">{{ err }}</p>
                            </div>
                        </div>
                        <div id="main" class="echarts_data" style="height: 80%;width: 500px;box-shadow: 10px 10px 5px rgba(0,0,0,0);float: left;margin-top: 80px;margin-left: 100px"></div>
                        <script type="text/javascript">
                            var myChart=echarts.init(document.getElementById('main'));
                            var option={
                                title:{text:'设备列表',
                                textStyle:{
                                    fontWeight:'normal',
                                    color:'white'
                                }},
                                series:[
                                    {
                                         type:'pie',
                                         radius:'55%',
                                         name:'设备列表',
                                         data:[
                                             {value:{{ online }}, name:'在线设备'},
                                             {value:{{ offline }}, name:'离线设备'},
                                             {value:{{ err }}, name:'异常设备'},
                                         ]
                                    }
                                ]
                            };
                            myChart.setOption(option);
                        </script>
                    </div>
					<div class="portlet box blue" style="margin-top: 0px;">
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="btn-group">
									<button id="triggerBtn" style="background-color: #0275d8;font-size: 20px">添加设备</button>
                                    <div id="myModal" class="modal1">
                                        <div class="modal1-content">
                                            <div class="modal1-header">
                                                <h2></h2>
                                                <span id="closeBtn" class="close1" >×</span>
                                            </div>
                                            <div class="modal1-body">
                                                <div id="add_device">
                                                    <div id="triangle"></div>
                                                <h1>添加设备</h1>
                                                <form method="POST" action="{% url 'device:add' %}" class="add_device">
                                                    <input type="text" name="device_name" placeholder="设备名"/>
                                                    <input type="text" name="imsi" placeholder="imsi号" />
                                                    <input type="submit" value="添加" />
                                                    {% csrf_token %}
                                                </form>
                                                </div>
                                            </div>
                                            <div class="modal1-footer">
                                                <h3></h3>
                                            </div>
                                        </div>
                                    </div>
                                    <script type="text/javascript" src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js/modalBox.js"></script>
								</div>
							</div>
							<table class="table table-striped table-hover table-bordered" id="sample_editable_1">
								<thead>
									<tr>
										<th style="font-size: 20px">状态</th>
										<th style="font-size: 20px">设备名称</th>
										<th style="font-size: 20px">设备id</th>
                                        <th style="font-size: 20px">操作</th>
									</tr>
								</thead>
								<tbody>
									{% for device in devices %}
                                        <tr >
                                            <td style="font-size: 20px">{{ device.get_status_display }}</td>
                                            <td style="font-size: 20px"><a href="{% url 'device:detail' device.device_id %}" style="text-decoration: none">{{ device.device_name }}</a></td>
                                            <td style="font-size: 20px"><a href="{% url 'device:detail' device.device_id %}" style="text-decoration: none">{{ device.device_id }}</a></td>
                                            <td style="font-size: 20px" class="center"><a href="#" onclick="confirm_delete()" style="text-decoration: none">删除</a>
                                            <form style="display: none;"id="safe_delete" action="{% url 'device:delete' device.device_id %}" method="POST">
                                                {% csrf_token %}
                                                <button type="submit"></button>
                                            </form></td>
									    </tr>
                                    {% endfor %}
								</tbody>
                                <script>
                                       function confirm_delete() {
                                           layer.open({
                                               title: "确认删除",
                                               content: "确认删除这个设备",
                                               yes: function (index, layero) {
                                                   $('form#safe_delete button').click();
                                                   layer.close();
                                               }
                                           })
                                       }
                                    </script>
							</table>
						</div>
					</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
			<!-- END PAGE CONTENT -->
		</div>
    </div>
{% endblock %}
</html>

templates/login1.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>登录注册</title>

<link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/font-awesome.min.css">
<link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com//css1/style.css">

</head>
<body>

<div class="materialContainer">
	<div class="box">
        <span>绿色农场</span>
		<div class="title">登录</div>
        <form method="post" action="{% url 'users:login' %}">
            <div class="input">
			<label for="name">用户名</label>
			<input type="text" name="username" id="name">
			<span class="spin"></span>
		</div>
            <div class="input">
                <label for="pass">密码</label>
                <input type="password" name="password" id="pass">
                <span class="spin"></span>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips">{% for key,error in login_form.errors.items %}{{error}}{% endfor %}{{msg}}</div>
            <div class="button login">
			<button type="submit">
				<span>登录</span>
				<i class="fa fa-check"></i>
			</button>
		</div>
        {% csrf_token %}
        </form>
		<a href="{% url 'users:reset_password' %}" class="pass-forgot">忘记密码？</a>
	</div>

	<div class="overbox">
		<div class="material-button alt-2">
			<span class="shape"></span>
		</div>
		<div class="title">注册</div>
        <form method="post" action="{% url 'users:register' %}">
            <div class="input" style="margin-top: 5px">
                <label for="username">用户名</label>
                <input type="text" name="username" id="username">
                <span class="spin"></span>
		     </div>
            <div class="input" style="margin-top: 5px">
                <label for="email">邮箱</label>
                <input type="email" name="email" id="email">
                <span class="spin"></span>
            </div>
            <div class="input" style="margin-top: 5px">
                <label for="password1">密码</label>
                <input type="password" name="password1" id="password1">
                <span class="spin"></span>
            </div>
            <div class="input" style="margin-top: 5px">
                <label for="password2">确认密码</label>
                <input type="password" name="password2" id="password2">
                <span class="spin"></span>
            </div>
            <div class="button">
                <button>
                    <span>注册</span>
                </button>
            </div>
            {% csrf_token %}
        </form>
	</div>

</div>

<script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com/js1/jquery.min.js"></script>
<script src="https://first-1257059002.cos.ap-nanjing.myqcloud.com//js1/index.js"></script>



</body>
</html>

templates/reset_password.html
<!DOCTYPE html>
<html lang="en" >
<head>
<meta charset="UTF-8">
<title>找回密码</title>

<link rel="stylesheet" href="https://first-1257059002.cos.ap-nanjing.myqcloud.com/css/reset_password.css">

</head>
<body>

<div class="container">
  <div class="brand-logo"></div>
  <div class="brand-title">找回密码</div>
  <div class="inputs">
      <form method="POST" action="{% url 'users:reset_password' %}">
          <label>注册邮箱</label>
          <input type="email"  name="email" placeholder="请填写注册邮箱" />
          <div class="error btns login-form-tips" id="jsLoginTips">{{msg}}</div>
          <button type="submit">确定</button>
          {% csrf_token %}
      </form>
  </div>
</div>

  
</body>
</html>